name: Publish

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and release the installable python package.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Build package
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python setup.py bdist_wheel sdist
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          files: dist/*
      - name: Upload to PyPi
        run: |
          pip install twine
          twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*.whl
